#!/usr/bin/env bash
# script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

Contents=$(ls)
for File in $Contents; do
	echo "$File" | cut -d '-' -f2
done
